name: tests_macos

on:
  push:
  pull_request:

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- ubuntu-latest
          #- windows-latest
          - macOS-latest
        nim_version:
          - '1.2.0'
          - 'stable'
    needs: before
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v1
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}

      - name: Install sdl2
        run: |
          git clone https://github.com/nickgravelyn/sdl2-mac-build
          cd sdl2-mac-build
          download
          build
      - name: Install freeGLUT
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install freeglut

      - name: Build tests
        run: |
          cd tests
          for file in $(ls -v test*.nim); do
            echo "test: $file"
            nim c $file
            timeout 2 xvfb-run --auto-servernum --server-num=1 ./${file%%.nim} || [ $? -eq ${{ env.TIMEOUT_EXIT_STATUS }} ]
          done
        shell: bash
